export class Labels {

  public static en_IN: any = {
    labels: {
      header: {
        logo_mini: 'SA',
        logo_lg: 'School Admin',
        profile_btn: 'Profile',
        sign_out_btn: 'Sign out',
        1: 'Administrator',
        2: 'Teacher',
        3: 'Transportation'
      },
      footer: {
        gtt_btn: 'Go To Top',
        copy_right: 'Copyright ',
        year: ' 2018 ',
        company_name: 'VisionSoftware',
        msg: ' All rights reserved.'
      },
      side_menu: {
        name_nav: 'MAIN NAVIGATION',
        name_dashboard: 'Dashboard',
        name_class: 'Classes',
        add_division: 'Add Division',
        list_division: 'Division List',
        add_class: 'Add Class',
        list_class: 'Class List',
        name_teacher: 'Teacher\'s',
        add_teacher: 'Add Teacher',
        list_teacher: 'Teacher\'s List',
        name_student: 'Students',
        add_student: 'Add Student',
        list_student: 'Student\'s List',
        name_attendance: 'Attendance',
        add_attendance: 'Mark Attendance',
        list_attendance: 'Attendance Sheet',
        name_home_work: 'Home Work',
        add_home_work: 'Assign Home Work',
        list_home_work: 'Home Work List',
        name_time_table: 'Time Table',
        add_day: 'Add Day',
        list_day: 'Days List',
        add_time_table: 'Create Time Table',
        list_time_table: 'Time Tables',
        add_exam_time_table: 'Create Exam Time Table',
        list_exam_time_table: 'Exam Time Tables',
        name_result: 'Results',
        add_subject: 'Add Subject',
        list_subject: 'Subjects List',
        add_exam: 'Create Exam',
        list_exam: 'Exam List',
        add_marks: 'Assign Marks',
        list_marks: 'Result Board',
        name_driver: 'Drivers',
        add_driver: 'Add Driver',
        list_driver: 'Driver\'s List',
        name_bus: 'Buses',
        add_bus: 'Add Bus',
        list_bus: 'Bus List',
        name_route: 'Routes',
        add_route: 'Add Route',
        list_route: 'Route List',
        name_library: 'Library',
        add_book: 'Add Book',
        list_book: 'Book List',
        add_book_type: 'Add Book Type',
        list_book_ype: 'Book Type List',
        name_gallery: 'Gallery',
        add_album: 'Create Album',
        list_album: 'Album List',
        add_image: 'Add Images',
        list_gallery: 'List Gallery',
        name_notification: 'Notifications',
        add_notification: 'Create Notification',
        list_notification: 'Notification List',
        add_bus_stop: 'Add Bus Stop',
        list_bus_stop: 'Bus Stop List'
      },
      dashboard: {
        head_title: 'DashBoard',
        class_box: 'Classes',
        teacher_box: 'Teachers',
        student_box: 'Students',
        driver_box: 'Drivers',
        bus_box: 'Buses',
        route_box: 'Routes',
        bus_stop_box: 'Bus Stops',
        attendance_box: 'Attendance',
        home_work_box: 'Home Works',
        time_table_box: 'Time Tables',
        result_box: 'Results',
        notification_box: 'Notifications',
        division_box: 'Divisions',
        book_box: 'Books',
        album_box: 'Albums',
        view_detail: 'View Details'
      },
      table: {
        common: {
          drop_menu_option1_title: 'Columns To Show',
          drop_menu_option2_title: 'Entries To Show',
          head_action_col: 'ACTION',
          head_sr_no: 'SR NO.'
        },
        division: {
          table_title: 'List of Divisions',
          add_btn: 'Add Division',
          divisionName: 'DIVISION NAME',
          divisionDesc: 'DIVISION DESCRIPTION',
        },
        class: {
          table_title: 'List of Classes',
          add_btn: 'Add Class',
          className: 'CLASS',
          division: 'DIVISION',
          teacher: 'TEACHER'
        },
        teacher: {
          table_title: 'List of Teacher\'s',
          add_btn: 'Add Teacher',
          firstName: 'FIRST NAME',
          lastName: 'LAST NAME',
          contactNo: 'MOBILE NO.',
          email: 'EMAIL ID'
        },
        student: {
          table_title: 'List of Student\'s',
          add_btn: 'Add Student',
          rollNo: 'ROLL NO.',
          firstName: 'FIRST NAME',
          lastName: 'LAST NAME',
          class: 'CLASS',
          division: 'DIVISION',
          username: 'USERNAME'
        },
        attendance: {
          table_title: 'Attendance Sheet',
          add_btn: 'Mark Attendance',
          classes: 'CLASS',
          division: 'DIVISION',
          date: 'DATE',
          subject: 'SUBJECT',
          status: 'STATUS'
        },
        homeW: {
          table_title: 'List of Home Work',
          add_btn: 'Assign Home Work',
          classId: 'CLASS',
          division: 'DIVISION',
          homeWorkDate: 'DATE',
          subject: 'SUBJECT',
          status: 'STATUS'
        },
        day: {
          table_title: 'Days',
          add_btn: 'Add Day',
          name: 'NAME',
        },
        timeT: {
          table_title: 'Time Tables',
          add_btn: 'Create Time Table',
          title: 'TITLE',
          classes: 'CLASS',
          division: 'DIVISION',
          subject: 'SUBJECT',
          time: 'TIME',
          day: 'DAY'
        },
        examTimeT: {
          table_title: 'Exam Time Tables',
          add_btn: 'Create Exam Time Table',
          examId: 'EXAM',
          classes: 'CLASS',
          division: 'DIVISION',
          subject: 'SUBJECT',
          examDate: 'EXAM DATE',
          examTime: 'EXAM TIME'
        },
        subject: {
          table_title: 'List of Subjects',
          add_btn: 'Add Subject',
          subjectName: 'SUBJECT NAME',
          classId: 'CLASS',
          description: 'DESCRIPTION'
        },
        exam: {
          table_title: 'List of Exams',
          add_btn: 'Add Exam',
          examName: 'EXAM NAME',
          examDesc: 'DESCRIPTION'
        },
        result: {
          table_title: 'Result Board',
          add_btn: 'Add Result',
          name: 'NAME',
          class: 'CLASS',
          division: 'DIVISION',
          count: 'NUMBER OF STUDENTS',
          result: 'CLASS RESULT'
        },
        driver: {
          table_title: 'List of Drivers',
          add_btn: 'Add Driver',
          firstName: 'FIRST NAME',
          lastName: 'LAST NAME',
          contactNo: 'MOBILE'
        },
        bus: {
          table_title: 'List of Bus',
          add_btn: 'Add Bus',
          busNo: 'BUS NO.',
          driver: 'DRIVER NAME',
          route: 'ROUTE NAME'
        },
        busS: {
          table_title: 'List of Bus Stop',
          add_btn: 'Add Bus Stop',
          name: 'STOP NAME',
        },
        route: {
          table_title: 'List of Routes',
          add_btn: 'Add Route',
          routeName: 'ROUTE NAME',
          from: 'FROM',
          to: 'TO'
        },
        bookType: {
          table_title: 'List of Book Types',
          add_btn: 'Add Book Type',
          name: 'BOOK TYPE NAME',
        },
        book: {
          table_title: 'List of Books',
          add_btn: 'Add Book',
          bookName: 'NAME',
          authors: 'AUTHOR',
          bookType: 'BOOK TYPE',
          subject: 'SUBJECT',
          isbn: 'ISBN'
        },
        album: {
          table_title: 'List of Albums',
          add_btn: 'Create Album',
          albumName: 'ALBUM NAME',
        },
        gallery: {
          table_title: 'Gallery List',
          add_btn: 'Add Images',
          albumName: 'ALBUM NAME',
          title: 'TITLE',
        },
        notification: {
          table_title: 'List of Notifications',
          add_btn: 'Send Notification',
          title: 'TITLE',
          class: 'CLASS',
          division: 'DIVISION',
          date: 'DATE'
        }
      },
      page_title: {
        new: 'Add',
        view: 'Details of',
        edit: 'Edit',
        bookType: 'Book Type',
        book: 'Book',
        bus: 'Bus',
        driver: 'Driver',
        class: 'Class',
        teacher: 'Teacher',
        student: 'Student',
        login: 'Login',
        bus_stop: 'Bus Stop',
        route: 'Route',
        division: 'Division',
        profile: 'Profile',
        album: 'Album',
        gallery: 'Gallery',
        subject: 'Subject',
        exam: 'Exam',
        day: 'Day',
        timeTable: 'Time Table',
        examTimeTable: 'Exam Time Table',
        homeWork: 'Home Work'
      },
      form_labels: {
        user_f_name: 'First Name',
        user_l_name: 'Last Name',
        user_contact_no: 'Mobile Number',
        user_address: 'Address',
        user_email: 'Email Id',
        user_password: 'Password',
        user_dob: 'Date of Birth',
        user_f_name_placeholder: 'Enter First Name',
        user_l_name_placeholder: 'Enter Last Name',
        user_contact_no_placeholder: 'Enter Mobile Number',
        user_address_placeholder: 'Enter Address',
        user_email_placeholder: 'Enter Email Id',
        user_password_placeholder: 'Enter Password',

        mobile_prefix: '+91',
        modal_status: 'Status',
        modal_add_msg: ' is added successfully.',
        modal_update_msg: ' is updated successfully.',
        modal_delete_msg: 'Are you sure you want to delete this entry!',

        login_email: 'Email Id',
        login_pass: 'Password',
        login_email_placeholder: 'Enter Email Id',
        login_pass_placeholder: 'Enter Password',

        ok_btn: 'OK',
        submit_btn: 'Submit',
        back_btn: 'Back',
        update_btn: 'Update',
        delete_btn: 'Delete',

        bus_no: 'Bus No.',
        bus_owner: 'Owner Name',
        bus_driver: 'Driver Name',
        bus_route: 'Bus Route',
        bus_contact_no: 'Contact No.',
        bus_no_placeholder: 'Enter Bus No.',
        bus_owner_placeholder: 'Enter Owner Name',
        bus_driver_placeholder: 'Select Driver',
        bus_route_placeholder: 'Select Bus Route',
        bus_contact_no_placeholder: 'Enter Contact No.',

        stop_name: 'Bus Stop Name',
        stop_lat: 'Bust Stop Latitude',
        stop_lng: 'Bust Stop Longitude',
        map_search: 'Search',
        map_search_placeholder: 'Search the location',
        stop_name_placeholder: 'Enter Bus Stop Name',
        stop_lat_placeholder: 'Click on Map or Search',
        stop_lng_placeholder: 'Click on Map or Search',

        driver_f_name: 'First Name',
        driver_l_name: 'Last Name',
        driver_adhar_no: 'Adhar No.',
        driver_mobile_no: 'Mobile No.',
        driver_email: 'Email ID',
        driver_position: 'Position',
        driver_profile: 'Profile',
        driver_address: 'Address',
        driver_username: 'User Name',
        driver_pass: 'Password',
        driver_bus: 'Bus No.',
        driver_dob: 'Date of Birth',
        driver_f_name_placeholder: 'Enter First Name',
        driver_l_name_placeholder: 'Enter Last Name',
        driver_adhar_no_placeholder: 'Enter Adhar Number',
        driver_mobile_no_placeholder: 'Enter Mobile Number',
        driver_email_placeholder: 'Enter Email ID',
        driver_address_placeholder: 'Enter Address',
        driver_username_placeholder: 'Enter User Name',
        driver_pass_placeholder: 'Enter Password',
        driver_bus_placeholder: 'Select Bus',
        driver_position_placeholder: 'Enter Position',

        class_name: 'Standard',
        division_name: 'Division Name',
        division_desc: 'Division Description',
        class_desc: 'Class Descrption',
        class_teacher: 'Class Teacher',
        class_name_placeholder: 'Enter Standard',
        division_name_placeholder: 'Enter Division Name',
        division_desc_placeholder: 'Enter Division Description',
        class_desc_placeholder: 'Enter Class Description',
        class_teacher_placeholder: 'Select Class Teacher',

        teacher_f_name: 'First Name',
        teacher_l_name: 'Last Name',
        teacher_dob: 'Date of Birth',
        teacher_contactNo: 'Mobile No.',
        teacher_email: 'Email Id',
        teacher_profile: 'Profile Pic',
        teacher_designation: 'Designation',
        teacher_address: 'Address',
        teacher_pass: 'Password',
        teacher_f_name_placeholder: 'Enter First Name',
        teacher_l_name_placeholder: 'Enter Last Name',
        teacher_contactNo_placeholder: 'Enter Mobile Number',
        teacher_email_placeholder: 'Enter Email Id',
        teacher_designation_placeholder: 'Enter Designation',
        teacher_address_placeholder: 'Enter Address',
        teacher_pass_placeholder: 'Enter Password',

        student_f_name: 'First Name',
        studengt_l_name: 'Last Name',
        student_father_name: 'Father Name',
        studengt_mother_name: 'Mother Name',
        studengt_guardian_name: 'Guardian Name',
        student_father_contactNo: 'Father Mobile No.',
        student_mother_contactNo: 'Mother Mobile No.',
        student_guardian_contactNo: 'Guardian Mobile No.',
        student_emergency_contactNo: 'Emergency Mobile No.',
        student_email: 'Email Id',
        student_profile: 'Profile Pic',
        student_roll: 'Roll No.',
        student_adharNo: 'Adhar No.',
        student_prn: 'PRN No.',
        student_dob: 'Date of Birth',
        student_bloodG: 'Blood Group',
        student_class: 'Class Name',
        student_division: 'Division Name',
        student_address: 'Address',
        student_route: 'Route Name',
        student_pass: 'Password',
        student_stop: 'Bus Stop',
        student_gender: 'Gender',
        student_admission_date: 'Admission Date',
        student_f_name_placeholder: 'Enter First Name',
        studengt_l_name_placeholder: 'Enter Last Name',
        student_father_name_placeholder: 'Enter Father\'s Name',
        studengt_mother_name_placeholder: 'Enter Mother\'s Name',
        studengt_guardian_name_placeholder: 'Enter Guardian\'s Name',
        student_father_contactNo_placeholder: 'Enter Father\'s Mobile No.',
        student_mother_contactNo_placeholder: 'Enter Mother\'s Mobile No.',
        student_guardian_contactNo_placeholder: 'Enter Guardian\'s Mobile No.',
        student_emergency_contactNo_placeholder: 'Enter Emergency Mobile No.',
        student_email_placeholder: 'Enter Email Id',
        student_roll_placeholder: 'Enter Roll No.',
        student_adharNo_placeholder: 'Enter Adhar No.',
        student_prn_placeholder: 'Enter PRN No.',
        student_bloodG_placeholder: 'Enter Blood Group',
        student_class_placeholder: 'Select Class Name',
        student_division_placeholder: 'Select Division Name',
        student_address_placeholder: 'Enter Address',
        student_route_placeholder: 'Select Route Name',
        student_stop_placeholder: 'Select Bus Stop',
        student_pass_placeholder: 'Enter Password',
        student_gender_placeholder: 'Select Gender',

        route_name: ' Route Name',
        route_start: 'Starting Bus Stop',
        route_end: 'Last Bus Stop',
        pick_up: 'Pick Up Stops',
        route_name_placeholder: 'Enter Route Name',
        route_start_placeholder: 'Select Starting Bus Stop',
        route_end_placeholder: 'Select Last Bus Stop',
        pick_up_placeholder: 'Select Pick Up Stops',
        pick_up_add_btn: 'Add Pick Up',

        book_type: 'Book Type',
        book_type_placeholder: 'Enter Book Type',

        book_name: 'Book Name',
        book_type_name: 'Book Type',
        book_subject: 'Subject',
        book_author: 'Authors',
        book_publisher: 'Publisher',
        book_desc: 'Description',
        book_edition: 'Edition',
        book_cover_pic: 'Cover Pic',
        book_isbn: 'Isbn',
        book_name_placeholder: 'Enter Book Name',
        book_type_name_placeholder: 'Select Book Type',
        book_subject_placeholder: 'Enter Subject',
        book_author_placeholder: 'Enter Authors',
        book_publisher_placeholder: 'Enter Publisher',
        book_desc_placeholder: 'Enter Description',
        book_edition_placeholder: 'Enter Edition',
        book_isbn_placeholder: 'Enter Isbn',

        album_name: 'Album Name',
        album_img: 'Album Cover Pic',
        album_name_placeholder: 'Enter Album Name',

        gallery_title: 'Title',
        gallery_album: 'Album',
        gallery_img: 'Gallery Image',
        gallery_title_placeholder: 'Enter Title',
        gallery_album_placeholder: 'Select Album',

        subject_name: 'Subject Name',
        subject_desc: 'Description',
        subject_class: 'Class Name',
        subject_name_placeholder: 'Enter Subject Name',
        subject_desc_placeholder: 'Enter Description',
        subject_class_placeholder: 'Select Class',

        exam_name: 'Exam Name',
        exam_desc: 'Description',
        exam_name_placeholder: 'Enter Exam Name',
        exam_desc_placeholder: 'Enter Description',

        day_name: 'Day Name',
        day_name_placeholder: 'Enter Day Name',

        time_table_title: 'Title',
        time_table_class: 'Class',
        time_table_division: 'Division',
        time_table_subject: 'Subject',
        time_day: 'Day',
        time_table_time: 'Time',
        time_table_title_placeholder: 'Enter Title',
        time_table_class_placeholder: 'Select Class',
        time_table_division_placeholder: 'Select Division',
        time_table_subject_placeholder: 'Select Subject',
        time_day_placeholder: 'Select Day',
        time_table_time_placeholder: 'Enter Time',

        exam_time_table_exam: 'Exam',
        exam_time_table_class: 'Class',
        exam_time_table_division: 'Division',
        exam_time_table_subject: 'Subject',
        exam_time_date: 'Date',
        exam_time_table_time: 'Time',
        exam_time_table_exam_placeholder: 'Select Exam',
        exam_time_table_time_placeholder: 'Enter Time',

        home_work_date: 'Assigned Date',
        home_work_desc: 'Description',
        home_work_class: 'Class',
        home_work_division: 'Division',
        home_work_subject: 'Subject',
        home_work_status: 'Home Work Status',
        home_work_attachment: 'Attachment Pic',
        home_work_description_placeholder: 'Enter Description',
        home_work_class_placeholder: 'Select Class',
        home_work_division_placeholder: 'Select Division',
        home_work_subject_placeholder: 'Select Subject',
        home_work_status_placeholder: 'Select Status',
      }
    }
  };

}
